### ISSUE TITLE
Submitted link on r/programming

### ISSUE THREAD

**Issue by runvnc** [jamesbowman/j1#1]
Hello I submitted a link to your excamera j1 page on reddit.com/r/programming on the off chance you didn't see the thread and wanted to read the comments or reply http://www.reddit.com/r/programming/comments/326w7n/the_j1_forth_cpu/

**Comment by jamesbowman** [comment]
Yes, thanks very much - I did enjoy reading the comments; it is good to see
people being so positive about Forth.

The page had a lot of traffic today:

[image: Inline image 1]

J.

On Sat, Apr 11, 2015 at 7:10 PM, Jason Livesay notifications@github.com
wrote:

> Hello I submitted a link to your excamera j1 page on
> reddit.com/r/programming on the off chance you didn't see the thread and
> wanted to read the comments or replyhttp://
> www.reddit.com/r/programming/comments/326w7n/the_j1_forth_cpu/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jamesbowman/j1/issues/1.

## 

James Bowman
http://www.excamera.com/
